nome = str(input('Informe seu nome completo: ')).strip()
print('Seu nome completo é {}'.format(nome))
separado = nome.split()
print('Seu primeiro nome é: {}' .format(separado[0]))
print('Seu último nome é: {}' .format(separado[len(separado) -1]))
